### PR TITLE
Fixed incompatibility with new "elastic" skin from Roundcube >= 1.4.0

### PR DESCRIPTION
**Pull request by CoolMcFly81**

### CODE REVIEW

**Comment by niesel** [comment]
Works for me. :-) Thumbs up!

**Comment by ricardo777** [comment]
Does not work when using custom elastic skin. because of: `if(rcmail.env.skin == 'elastic') {`

**Comment by bensuffolk** [comment]
When will this be merged? I have just upgraded Roundcube and would like to keep using this plugIn with the new elastic skin.

**Comment by ricardo777** [comment]
> When will this be merged? I have just upgraded Roundcube and would like to keep using this plugIn with the new elastic skin.

Why don't you use the commit yourself. Then you don't have to wait.

**Comment by bensuffolk** [comment]
I will, but be nice for it to get in the branch so it’s there for everybody.

**Comment by agabellini** [comment]
Hello,

@CoolMcFly81 I tried your fork with 1.5beta, but id didn't work... Are you able to try and eventually build a patch?

Andrea

**Comment by agabellini** [comment]
Hello,

thanks for the merge, but it didn't works with 1.5 RC.

Andrea


> Hello,
> 
> @CoolMcFly81 I tried your fork with 1.5beta, but id didn't work... Are you able to try and eventually build a patch?
> 
> Andrea

**Pull request merged**
